Use `exist_ok=False` for os.makedirs
tsroten/fcache pull request #41
Opened 2024-02-15 16:38 UTC by dimitris-flyr

https://docs.python.org/3/library/os.html#os.makedirs

We receive `FileExistsError` when multiple processes use the same file cache

2024-02-17 20:52 UTC, tsroten commented
Hello! Thanks for your contribution! I'm a little confused on what you're attempting to accomplish here. Do you think you could describe what behavior you're trying to fix or change?

2024-02-19 15:13 UTC, dimitris-flyr commented
Hi @tsroten. The issue is when you have multiple processes using the same file cache. In that case, you end up with race conditions, where both processes are trying to create the same file and you receive a `FileExistsError`

2024-02-21 22:56 UTC, tsroten requested changes

2024-02-21 22:56 UTC, tsroten commented on src/fcache/cache.py
> +            os.makedirs(self.cache_dir, exist_ok=True)
```suggestion
        os.makedirs(self.cache_dir, exist_ok=True)
```

2024-02-22 17:39 UTC, merged